# Generated by Django 5.2 on 2026-03-23 23:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(max_length=128, unique=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('syn_count', models.IntegerField(default=0)),
                ('synack_count', models.IntegerField(default=0)),
                ('ack_count', models.IntegerField(default=0)),
                ('rst_count', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syn_threshold', models.IntegerField(default=50)),
                ('syn_window_seconds', models.IntegerField(default=10)),
                ('handshake_completion_min_ratio', models.FloatField(default=0.2)),
                ('rst_threshold', models.IntegerField(default=20)),
                ('rst_window_seconds', models.IntegerField(default=10)),
                ('hijack_seq_jump', models.IntegerField(default=500000)),
                ('alert_cooldown_seconds', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterfaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('flags', models.CharField(max_length=16)),
                ('seq', models.BigIntegerField(blank=True, null=True)),
                ('ack', models.BigIntegerField(blank=True, null=True)),
                ('length', models.IntegerField()),
                ('protocol', models.CharField(default='TCP', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_type', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('dedup_key', models.CharField(db_index=True, max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
