# Generated by Django 5.0.3 on 2026-03-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsession',
            name='alert_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringsession',
            name='mode',
            field=models.CharField(choices=[('live', 'Live'), ('pcap', 'PCAP')], default='live', max_length=16),
        ),
        migrations.AddField(
            model_name='monitoringsession',
            name='packet_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringsession',
            name='pcap_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitoringsession',
            name='processing_ms_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
